// This file is auto-generated by scripts/generate-env.js
// DO NOT EDIT MANUALLY - Changes will be overwritten
// Configure values in .env file instead

export const environment = {
  "production": true,
  "apiUrl": "https://api.3dime.com",
  "firebase": {
    "apiKey": "",
    "authDomain": "",
    "projectId": "",
    "storageBucket": "",
    "messagingSenderId": "",
    "appId": ""
  }
};
